"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import struct
import json
import os
import time
import base64

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives import hashes, hmac

channel_session_keys = {}

def get_channel_session_key(channel: int) -> bytes:
    if channel not in channel_session_keys or channel_session_keys[channel] is None:
        channel_session_keys[channel] = os.urandom(16)

    return channel_session_keys[channel]

class Encoder:
    def __init__(self, secrets: bytes):
        """
        You **may not** change the arguments or returns of this function!

        :param secrets: Contents of the secrets file generated by
            ectf25_design.gen_secrets
        """
        # TODO: parse your secrets data here and run any necessary pre-processing to
        #   improve the throughput of Encoder.encode

        # Load the json of the secrets file
        secrets = json.loads(secrets)

        self.hmac_auth_key = base64.b64decode(secrets["hmac_auth_key"])
        self.subupdate_salt = base64.b64decode(secrets["subupdate_salt"])
        self.emergency_key = base64.b64decode(secrets["emergency_key"])

    def encode(self, channel: int, frame: bytes, timestamp: int) -> bytes:
        """The frame encoder function

        This will be called for every frame that needs to be encoded before being
        transmitted by the satellite to all listening TVs

        You **may not** change the arguments or returns of this function!

        :param channel: 32b unsigned channel number. Channel 0 is the emergency
            broadcast that must be decodable by all channels.
        :param frame: Frame to encode. Max frame size is 64 bytes.
        :param timestamp: 64b timestamp to use for encoding. **NOTE**: This value may
            have no relation to the current timestamp, so you should not compare it
            against the current time. The timestamp is guaranteed to strictly
            monotonically increase (always go up) with subsequent calls to encode

        :returns: The encoded frame, which will be sent to the Decoder
        """

        channel_key = self.emergency_key if channel == 0 else get_channel_session_key(channel)

        iv = os.urandom(16) # Initialization vector introduces randomness

        aes_cipher = Cipher(algorithms.AES(channel_key), modes.CBC(iv))

        unix_time = int(time.time())

        # timestamp + unix time + frame
        frame_data = struct.pack("<QQ", timestamp, unix_time) + frame

        # Pad to make data multiple of 16 bytes (block size)
        padder = padding.PKCS7(128).padder()
        padded_body = padder.update(frame_data) + padder.finalize()

        # Encrypt padded data
        encryptor = aes_cipher.encryptor()
        encrypted_body = encryptor.update(padded_body) + encryptor.finalize()

        # Compute HMAC and prepend to body
        h = hmac.HMAC(self.hmac_auth_key, hashes.SHA256())

        h.update(encrypted_body)

        hmac_signature = h.finalize()

        channel_bytes = struct.pack("<I", channel)

        return channel_bytes + hmac_signature + iv + encrypted_body


def main():
    """A test main to one-shot encode a frame

    This function is only for your convenience and will not be used in the final design.

    After pip-installing, you should be able to call this with:
        python3 -m ectf25_design.encoder path/to/test.secrets 1 "frame to encode" 100
    """
    parser = argparse.ArgumentParser(prog="ectf25_design.encoder")
    parser.add_argument(
        "secrets_file", type=argparse.FileType("rb"), help="Path to the secrets file"
    )
    parser.add_argument("channel", type=int, help="Channel to encode for")
    parser.add_argument("frame", help="Contents of the frame")
    parser.add_argument("timestamp", type=int, help="64b timestamp to use")
    args = parser.parse_args()

    encoder = Encoder(args.secrets_file.read())
    print(repr(encoder.encode(args.channel, args.frame.encode(), args.timestamp)))


if __name__ == "__main__":
    main()
