"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import json
import os
import base64
from pathlib import Path
import struct
from encoder import get_channel_session_key

from loguru import logger
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives import hashes, hmac

# Test: 
# 
# ../.venv/bin/python3.11 -m ectf25_design.gen_subscription ../global.secrets/secrets.json subscription.bin 0xdeadbeef 0 100 1 

def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription.

    The output of this will be passed to the Decoder using ectf25.tv.subscribe

    :param secrets: Contents of the secrets file generated by ectf25_design.gen_secrets
    :param device_id: Device ID of the Decoder
    :param start: First timestamp the subscription is valid for
    :param end: Last timestamp the subscription is valid for
    :param channel: Channel to enable
    """
    # TODO: Update this function to provide a Decoder with whatever data it needs to
    #   subscribe to a new channel

    # Load the json of the secrets file
    secrets = json.loads(secrets)

    hmac_auth_key = base64.b64decode(secrets["hmac_auth_key"])
    subupdate_salt = base64.b64decode(secrets["subupdate_salt"])

    channel_key = get_channel_session_key(channel)

    # Make subupdate key: hash(decoder_id + salt)
    def make_subupdate_key(decoder_id: int):
        prehash = decoder_id.to_bytes(4, 'big') + subupdate_salt
        
        hasher = hashes.Hash(hashes.SHA256())        
        hasher.update(prehash)

        return hasher.finalize()
    
    subupdate_key = make_subupdate_key(device_id)

    # Encrypt body using AES-CBC
    # We don't use AES-GCM because the encryption + authentication uses the same key, this is not a safe practice.
    # We will AES-CBC + HMAC separately 
    iv = os.urandom(16) # Initialization vector introduces randomness

    aes_cipher = Cipher(algorithms.AES(subupdate_key), modes.CBC(iv))

    body = struct.pack("<IQQI", device_id, start, end, channel)
    body = body + channel_key

    # Pad to make data multiple of 16 bytes (block size)
    padder = padding.PKCS7(128).padder()
    padded_body = padder.update(body) + padder.finalize()

    # Encrypt padded data
    encryptor = aes_cipher.encryptor()
    encrypted_body = encryptor.update(padded_body) + encryptor.finalize()

    # Compute HMAC and prepend to body
    h = hmac.HMAC(hmac_auth_key, hashes.SHA256())

    h.update(encrypted_body)

    hmac_signature = h.finalize()

    # print(f"HMAC: {hmac_signature.hex()}")
    # print(f"IV: {iv.hex()}")
    # print(f"Body: {encrypted_body.hex()}")

    return hmac_signature + iv + encrypted_body 


def parse_args():
    """Define and parse the command line arguments

    NOTE: Your design must not change this function
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Force creation of subscription file, overwriting existing file",
    )
    parser.add_argument(
        "secrets_file",
        type=argparse.FileType("rb"),
        help="Path to the secrets file created by ectf25_design.gen_secrets",
    )
    parser.add_argument("subscription_file", type=Path, help="Subscription output")
    parser.add_argument(
        "device_id", type=lambda x: int(x, 0), help="Device ID of the update recipient."
    )
    parser.add_argument(
        "start", type=lambda x: int(x, 0), help="Subscription start timestamp"
    )
    parser.add_argument("end", type=int, help="Subscription end timestamp")
    parser.add_argument("channel", type=int, help="Channel to subscribe to")
    return parser.parse_args()


def main():
    """Main function of gen_subscription

    You will likely not have to change this function
    """
    # Parse the command line arguments
    args = parse_args()

    subscription = gen_subscription(
        args.secrets_file.read(), args.device_id, args.start, args.end, args.channel
    )

    # Print the generated subscription for your own debugging
    # Attackers will NOT have access to the output of this (although they may have
    # subscriptions in certain scenarios), but feel free to remove
    #
    # NOTE: Printing sensitive data is generally not good security practice
    logger.debug(f"Generated subscription: {subscription}")

    # Open the file, erroring if the file exists unless the --force arg is provided
    with open(args.subscription_file, "wb" if args.force else "xb") as f:
        f.write(subscription)

    # For your own debugging. Feel free to remove
    logger.success(f"Wrote subscription to {str(args.subscription_file.absolute())}")


if __name__ == "__main__":
    main()
